class TestData:
    url = "http://192.168.254.13/ruralnet-v3-main/LoginForm.htm"
    user = "testing-ayu"
    password = "password1*"

    # Sell Insurance Test Data
    insured_lastname = "Cayetano"
    insured_firstname = "Peter"
    insured_middlename = "Silva"
    insured_date_of_birth = "02/05/1976"
    insured_gender = "Male"
    insured_phone_number = "09273981938"
    insured_address = "4568 Test Address"
    insured_province = "CEBU CITY, CEBU"
    insured_civil_status = "Single"
    insured_occupation = "Testing"
    insured_place_of_birth = "COLON CEBU"
    insured_sss_tin = "317137990"
    bene_lastname = "Zsa"
    bene_firstname = "Mary Rose"
    bene_middlename = "Camel"
    bene_relationship = "Cousin"
    amount_recieved = "460"
    family_lastname = "Cayetano"
    family_firstname = "Claire"
    family_middlename = "Ooopsie"
    family_dateofbirth = "05/06/2004"
    family_relationship = "Sibling"
    reference_client_id = "123456"
